# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.252"
    hooks:
      - id: ruff
  # - repo: https://github.com/google/yapf
  #   additional_dependencies: [toml]
  #   rev: "v0.32.0" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: yapf
